// Code generated by tui generate. DO NOT EDIT.
// Source: manager.gsx

package tui

import (
	"context"
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/cutx64/WhiteSoft/desktop/internal/launcher"
	"github.com/cutx64/WhiteSoft/desktop/internal/notes"
	tui "github.com/grindlemire/go-tui"
)

type Options struct {
	Root   string // directory holding the .note files (the manager browses it)
	Server string // path to server.mjs ("" = auto-detect)
	Node   string // node executable ("" = auto-detect)
	Port   int    // 0 = pick a free port when the server starts
	Open   bool   // open the browser as soon as the server is up
}

type manager struct {
	opts Options

	boards   *tui.State[[]notes.Board]
	detail   *tui.State[*notes.Detail]
	status   *tui.State[string]
	busy     *tui.State[string]
	serverUp *tui.State[bool]
	url      *tui.State[string]

	boardCur  *tui.State[int]
	pageCur   *tui.State[int]
	focus     *tui.State[int] // 0 = board list, 1 = page list
	filter    *tui.State[string]
	filtering *tui.State[bool]
	showAll   *tui.State[bool] // preview every text block of a page

	boardScroll *tui.State[int]
	pageScroll  *tui.State[int]
	boardRef    *tui.Ref
	pageRef     *tui.Ref

	srv     *launcher.Server
	loading bool
}

const helpLine = "j/k 移动 · tab 切换栏位 · enter 载入 / 浏览器打开 · o 打开 · s 服务 · / 搜索 · a 展开 · r 刷新 · q 退出"

func Manager(opts Options) *manager {
	m := &manager{
		opts:        opts,
		boards:      tui.NewState([]notes.Board{}),
		detail:      tui.NewState[*notes.Detail](nil),
		status:      tui.NewState(""),
		busy:        tui.NewState(""),
		serverUp:    tui.NewState(false),
		url:         tui.NewState(""),
		boardCur:    tui.NewState(0),
		pageCur:     tui.NewState(0),
		focus:       tui.NewState(0),
		filter:      tui.NewState(""),
		filtering:   tui.NewState(false),
		showAll:     tui.NewState(false),
		boardScroll: tui.NewState(0),
		pageScroll:  tui.NewState(0),
		boardRef:    tui.NewRef(),
		pageRef:     tui.NewRef(),
	}
	m.rescan()
	return m
}

func (m *manager) rescan() {
	boards, err := notes.Scan(m.opts.Root)
	if err != nil {
		m.status.Set("扫描目录失败：" + err.Error())
		return
	}
	m.boards.Set(boards)
	m.boardCur.Set(0)
	m.boardScroll.Set(0)
	m.detail.Set(nil)
	m.pageCur.Set(0)
	if len(boards) == 0 {
		m.status.Set("该目录下没有 .note 文件（可用网页端导入 PDF 新建）")
	} else {
		m.status.Set(fmt.Sprintf("发现 %d 个白板", len(boards)))
	}
}

func (m *manager) visibleBoards() []notes.Board {
	all := m.boards.Get()
	q := strings.ToLower(strings.TrimSpace(m.filter.Get()))
	if q == "" {
		return all
	}
	var out []notes.Board
	for _, b := range all {
		if strings.Contains(strings.ToLower(b.Name), q) {
			out = append(out, b)
		}
	}
	return out
}

func (m *manager) visiblePages() []notes.Page {
	d := m.detail.Get()
	if d == nil {
		return nil
	}
	q := strings.ToLower(strings.TrimSpace(m.filter.Get()))
	if q == "" {
		return d.Pages
	}
	var out []notes.Page
	for _, p := range d.Pages {
		if strings.Contains(strings.ToLower(pageHaystack(p)), q) {
			out = append(out, p)
		}
	}
	return out
}

func pageHaystack(p notes.Page) string {
	var b strings.Builder
	for _, t := range p.Texts {
		b.WriteString(t)
		b.WriteByte('\n')
	}
	return b.String()
}

func (m *manager) selectedBoard() *notes.Board {
	list := m.visibleBoards()
	i := m.boardCur.Get()
	if i < 0 || i >= len(list) {
		return nil
	}
	return &list[i]
}

func (m *manager) selectedPage() *notes.Page {
	list := m.visiblePages()
	i := m.pageCur.Get()
	if i < 0 || i >= len(list) {
		return nil
	}
	return &list[i]
}

func (m *manager) loadSelectedBoard(app *tui.App) {
	b := m.selectedBoard()
	if b == nil || m.loading {
		return
	}
	name, path := b.Name, b.Path
	m.loading = true
	m.busy.Set("正在载入 " + name + " …")
	go func() {
		d, err := notes.Load(path, func(done, total int) {
			app.QueueUpdate(func() {
				m.busy.Set(fmt.Sprintf("正在载入 %s … %d/%d 页", name, done, total))
			})
		})
		app.QueueUpdate(func() {
			m.loading = false
			if err != nil {
				m.busy.Set("载入失败：" + err.Error())
				return
			}
			m.detail.Set(d)
			m.pageCur.Set(0)
			m.pageScroll.Set(0)
			_, _, _, texts, withContent := d.Stats()
			m.busy.Set(fmt.Sprintf("%s：%d 页，其中 %d 页有内容，%d 段文字",
				d.Name, len(d.Pages), withContent, texts))
		})
	}()
}

func (m *manager) toggleServer(app *tui.App, open bool) {
	if m.srv != nil {
		if open {
			url := m.url.Get()
			if err := launcher.OpenBrowser(url); err != nil {
				m.status.Set("打开浏览器失败：" + err.Error())
			} else {
				m.status.Set("已在浏览器打开 " + url)
			}
			return
		}
		srv := m.srv
		m.srv = nil
		m.serverUp.Set(false)
		m.url.Set("")
		m.status.Set("正在停止服务 …")
		go func() {
			_ = srv.Stop()
			app.QueueUpdate(func() { m.status.Set("服务已停止") })
		}()
		return
	}

	cfg := launcher.Config{
		ServerJS: m.opts.Server,
		NodeBin:  m.opts.Node,
		Port:     m.opts.Port,
	}
	m.status.Set("正在启动 server.mjs …")
	go func() {
		srv, err := launcher.Start(context.Background(), cfg)
		app.QueueUpdate(func() {
			if err != nil {
				m.status.Set("启动失败：" + err.Error())
				return
			}
			m.srv = srv
			m.url.Set(srv.URL())
			m.serverUp.Set(true)
			m.status.Set("服务已启动 " + srv.URL())
			if open {
				if err := launcher.OpenBrowser(srv.URL()); err != nil {
					m.status.Set("服务已启动，但打开浏览器失败：" + err.Error())
				}
			}
		})
	}()
}

func (m *manager) move(delta int) {
	if m.focus.Get() == 0 {
		n := len(m.visibleBoards())
		m.boardCur.Update(func(v int) int { return clampInt(v+delta, 0, n-1) })
		return
	}
	n := len(m.visiblePages())
	m.pageCur.Update(func(v int) int { return clampInt(v+delta, 0, n-1) })
}

func (m *manager) scrollToCursor() {
	var ref *tui.Ref
	var cur, scroll *tui.State[int]
	if m.focus.Get() == 0 {
		ref, cur, scroll = m.boardRef, m.boardCur, m.boardScroll
	} else {
		ref, cur, scroll = m.pageRef, m.pageCur, m.pageScroll
	}
	el := ref.El()
	if el == nil {
		return
	}
	_, vpH := el.ViewportSize()
	if vpH <= 0 {
		return
	}
	y := scroll.Get()
	c := cur.Get()
	if c < y {
		scroll.Set(c)
	} else if c >= y+vpH {
		scroll.Set(c - vpH + 1)
	}
}

func (m *manager) Watchers() []tui.Watcher {
	return []tui.Watcher{
		tui.OnChange(m.boardCur, func(int) { m.scrollToCursor() }),
		tui.OnChange(m.pageCur, func(int) { m.scrollToCursor() }),
		tui.OnChange(m.focus, func(int) { m.scrollToCursor() }),
	}
}

func (m *manager) KeyMap() tui.KeyMap {
	quit := func(ke tui.KeyEvent) { ke.App().Stop() }
	return tui.KeyMap{
		tui.OnStop(tui.KeyCtrlC, quit),
		tui.OnStop(tui.Rune('q'), func(ke tui.KeyEvent) {
			if m.filtering.Get() {
				m.typeRune('q')
				return
			}
			quit(ke)
		}),
		tui.OnStop(tui.KeyTab, func(ke tui.KeyEvent) {
			m.focus.Update(func(v int) int { return 1 - v })
			m.scrollToCursor()
		}),
		tui.OnStop(tui.KeyUp, func(ke tui.KeyEvent) { m.move(-1) }),
		tui.OnStop(tui.KeyDown, func(ke tui.KeyEvent) { m.move(1) }),
		tui.OnStop(tui.Rune('k'), func(ke tui.KeyEvent) {
			if m.filtering.Get() {
				m.typeRune('k')
				return
			}
			m.move(-1)
		}),
		tui.OnStop(tui.Rune('j'), func(ke tui.KeyEvent) {
			if m.filtering.Get() {
				m.typeRune('j')
				return
			}
			m.move(1)
		}),
		tui.OnStop(tui.KeyLeft, func(ke tui.KeyEvent) { m.focus.Set(0) }),
		tui.OnStop(tui.KeyRight, func(ke tui.KeyEvent) { m.focus.Set(1) }),
		tui.OnStop(tui.KeyEnter, func(ke tui.KeyEvent) {
			if m.filtering.Get() {
				m.filtering.Set(false)
				return
			}
			if m.focus.Get() == 0 {
				m.loadSelectedBoard(ke.App())
				return
			}
			m.toggleServer(ke.App(), true)
		}),
		tui.OnStop(tui.KeyEscape, func(ke tui.KeyEvent) {
			if m.filtering.Get() {
				m.filtering.Set(false)
				m.filter.Set("")
				m.boardCur.Set(0)
				m.pageCur.Set(0)
				return
			}
			if m.filter.Get() != "" {
				m.filter.Set("")
				return
			}
			ke.App().Stop()
		}),
		tui.OnStop(tui.Rune('/'), func(ke tui.KeyEvent) {
			m.filtering.Set(true)
			m.focus.Set(0)
		}),
		tui.OnStop(tui.KeyBackspace, func(ke tui.KeyEvent) {
			if !m.filtering.Get() {
				return
			}
			f := m.filter.Get()
			if f == "" {
				return
			}
			r := []rune(f)
			m.applyFilter(string(r[:len(r)-1]))
		}),
		tui.OnStop(tui.Rune('r'), func(ke tui.KeyEvent) {
			if m.filtering.Get() {
				m.typeRune('r')
				return
			}
			m.rescan()
		}),
		tui.OnStop(tui.Rune('s'), func(ke tui.KeyEvent) {
			if m.filtering.Get() {
				m.typeRune('s')
				return
			}
			m.toggleServer(ke.App(), false)
		}),
		tui.OnStop(tui.Rune('o'), func(ke tui.KeyEvent) {
			if m.filtering.Get() {
				m.typeRune('o')
				return
			}
			m.toggleServer(ke.App(), true)
		}),
		tui.OnStop(tui.Rune('a'), func(ke tui.KeyEvent) {
			if m.filtering.Get() {
				m.typeRune('a')
				return
			}
			m.showAll.Set(!m.showAll.Get())
		}),
		tui.OnStop(tui.AnyRune, func(ke tui.KeyEvent) {
			if m.filtering.Get() {
				m.typeRune(ke.Char())
			}
		}),
	}
}

func (m *manager) typeRune(r rune) {
	if r == 0 {
		return
	}
	m.applyFilter(m.filter.Get() + string(r))
}

func (m *manager) applyFilter(f string) {
	m.filter.Set(f)
	m.boardCur.Set(0)
	m.pageCur.Set(0)
	m.boardScroll.Set(0)
	m.pageScroll.Set(0)
}

func humanSize(n int64) string {
	const unit = 1024
	if n < unit {
		return fmt.Sprintf("%d B", n)
	}
	div, exp := int64(unit), 0
	for v := n / unit; v >= unit && exp < 3; v /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f %cB", float64(n)/float64(div), "KMGT"[exp])
}

func boardSubtitle(b notes.Board) string {
	parts := []string{fmt.Sprintf("%d 页", b.PageCount)}
	if b.Images > 0 {
		parts = append(parts, fmt.Sprintf("%d 图", b.Images))
	}
	if b.HasPDF {
		parts = append(parts, "PDF")
	}
	parts = append(parts, humanSize(b.Size))
	return strings.Join(parts, " · ")
}

func typeBreakdown(p notes.Page) string {
	type kv struct {
		t int
		n int
	}
	list := make([]kv, 0, len(p.Types))
	for t, n := range p.Types {
		list = append(list, kv{t, n})
	}
	sort.Slice(list, func(i, j int) bool { return list[i].n > list[j].n })
	var parts []string
	for i, e := range list {
		if i >= 5 {
			break
		}
		parts = append(parts, fmt.Sprintf("%s×%d", notes.TypeName(e.t), e.n))
	}
	return strings.Join(parts, " ")
}

func pageTitle(p notes.Page) string {
	flags := []string{fmt.Sprintf("%d 元素", p.Elements)}
	if p.Ink > 0 {
		flags = append(flags, fmt.Sprintf("%d 墨迹点", p.Ink))
	}
	if p.Images > 0 {
		flags = append(flags, fmt.Sprintf("%d 图", p.Images))
	}
	if p.HasPDF {
		flags = append(flags, "PDF 背景")
	}
	return fmt.Sprintf("第 %d 页 · %s", p.Number, strings.Join(flags, " · "))
}

func (m *manager) previewLines(p notes.Page) []string {
	max := 4
	if m.showAll.Get() {
		max = 40
	}
	var out []string
	for i, t := range p.Texts {
		if i >= max {
			out = append(out, fmt.Sprintf("… 还有 %d 段", len(p.Texts)-max))
			break
		}
		out = append(out, t)
	}
	if len(out) == 0 {
		out = append(out, "（这一页没有文字内容）")
	}
	return out
}

func containsMath(p notes.Page) bool {
	for _, t := range p.Texts {
		if strings.Contains(t, "$") {
			return true
		}
	}
	return false
}

func clampInt(v, lo, hi int) int {
	if hi < lo {
		return lo
	}
	if v < lo {
		return lo
	}
	if v > hi {
		return hi
	}
	return v
}

func baseName(p string) string { return filepath.Base(p) }

func line(indent int, s string) string { return strings.Repeat(" ", indent) + s }

func (m *manager) boardRow(i int, b notes.Board) string {
	if m.focus.Get() == 0 && i == m.boardCur.Get() {
		return "  ▶ " + b.Name
	}
	return "    " + b.Name
}

func (m *manager) pageRow(i int, p notes.Page) string {
	if m.focus.Get() == 1 && i == m.pageCur.Get() {
		return "  ▶ " + pageTitle(p)
	}
	return "    " + pageTitle(p)
}

func (m *manager) boardHeadline(d *notes.Detail) string {
	sub := "  " + boardSubtitle(d.Board) + m.pdfLabel(d)
	return sub
}

func (m *manager) serverLabel() string {
	if m.serverUp.Get() {
		return "服务 " + m.url.Get()
	}
	return "服务未启动（s 启动）"
}

func (m *manager) pdfLabel(d *notes.Detail) string {
	if d == nil || !d.HasPDF {
		return ""
	}
	if d.PDFName == "" {
		return " · 内嵌 PDF"
	}
	return " · 内嵌 " + d.PDFName
}

func (m *manager) Render(app *tui.App) *tui.Element {
	boards := m.visibleBoards()
	detail := m.detail.Get()
	pages := m.visiblePages()
	page := m.selectedPage()
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
		tui.WithHeightPercent(100.00),
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithPadding(1),
	)
	__tui_2 := tui.New(
		tui.WithText("WhiteSoft 终端管理器"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(baseName(m.opts.Root)),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_1.AddChild(__tui_3)
	if m.serverUp.Get() {
		__tui_4 := tui.New(
			tui.WithText(line(0, m.serverLabel())),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green)),
		)
		__tui_1.AddChild(__tui_4)
	} else {
		__tui_5 := tui.New(
			tui.WithText(line(0, m.serverLabel())),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_1.AddChild(__tui_5)
	}
	__tui_0.AddChild(__tui_1)
	if m.status.Get() != "" {
		__tui_6 := tui.New(
			tui.WithText(line(2, m.status.Get())),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_6)
	}
	if m.busy.Get() != "" {
		__tui_7 := tui.New(
			tui.WithText(line(2, m.busy.Get())),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow)),
		)
		__tui_0.AddChild(__tui_7)
	}
	if m.filtering.Get() || m.filter.Get() != "" {
		__tui_8 := tui.New(
			tui.WithText(fmt.Sprintf("  筛选：%s▌", m.filter.Get())),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
		)
		__tui_0.AddChild(__tui_8)
	}
	__tui_9 := tui.New(
		tui.WithHR(),
		tui.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_9)
	__tui_10 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithFlexGrow(1),
	)
	__tui_11 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidth(40),
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Black)),
	)
	__tui_12 := tui.New(
		tui.WithText(fmt.Sprintf("  白板（%d）", len(boards))),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_11.AddChild(__tui_12)
	__tui_13 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithScrollbarStyle(tui.NewStyle().Foreground(tui.Cyan)),
		tui.WithScrollbarThumbStyle(tui.NewStyle().Foreground(tui.BrightCyan)),
		tui.WithScrollOffset(0, m.boardScroll.Get()),
	)
	m.boardRef.Set(__tui_13)
	if len(boards) == 0 {
		__tui_14 := tui.New(
			tui.WithText("（没有匹配的白板）"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_13.AddChild(__tui_14)
	}
	for i, b := range boards {
		_ = i
		if m.focus.Get() == 0 && i == m.boardCur.Get() {
			__tui_15 := tui.New(
				tui.WithText(m.boardRow(i, b)),
				tui.WithBackground(tui.NewStyle().Background(tui.BrightBlack)),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
			)
			__tui_13.AddChild(__tui_15)
		} else {
			__tui_16 := tui.New(
				tui.WithText(m.boardRow(i, b)),
			)
			__tui_13.AddChild(__tui_16)
		}
		if b.Err != "" {
			__tui_17 := tui.New(
				tui.WithText(line(6, b.Err)),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red)),
			)
			__tui_13.AddChild(__tui_17)
		} else {
			__tui_18 := tui.New(
				tui.WithText(line(6, boardSubtitle(b))),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_13.AddChild(__tui_18)
		}
	}
	__tui_11.AddChild(__tui_13)
	__tui_10.AddChild(__tui_11)
	__tui_19 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
	)
	if detail == nil {
		__tui_20 := tui.New(
			tui.WithText(line(2, "选中一个白板后按 enter 载入页列表。")),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_19.AddChild(__tui_20)
		__tui_21 := tui.New(
			tui.WithText(line(2, "载入只读取 .note，不会修改文件。")),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_19.AddChild(__tui_21)
	} else {
		__tui_22 := tui.New(
			tui.WithText(line(2, detail.Name)),
			tui.WithTextStyle(tui.NewStyle().Bold()),
		)
		__tui_19.AddChild(__tui_22)
		__tui_23 := tui.New(
			tui.WithText(m.boardHeadline(detail)),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_19.AddChild(__tui_23)
		if detail.HasMath() {
			__tui_24 := tui.New(
				tui.WithText(line(2, "含 LaTeX 公式源码")),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Magenta)),
			)
			__tui_19.AddChild(__tui_24)
		}
		__tui_25 := tui.New(
			tui.WithHR(),
			tui.WithBorder(tui.BorderSingle),
		)
		__tui_19.AddChild(__tui_25)
		if page != nil {
			__tui_26 := tui.New(
				tui.WithText(line(2, pageTitle(*page))),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
			)
			__tui_19.AddChild(__tui_26)
			__tui_27 := tui.New(
				tui.WithText(line(2, typeBreakdown(*page))),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_19.AddChild(__tui_27)
			if containsMath(*page) {
				__tui_28 := tui.New(
					tui.WithText(line(2, "这一页含公式")),
					tui.WithTextStyle(tui.NewStyle().Foreground(tui.Magenta)),
				)
				__tui_19.AddChild(__tui_28)
			}
			for __idx_0, l := range m.previewLines(*page) {
				_ = __idx_0
				__tui_29 := tui.New(
					tui.WithText(line(4, l)),
				)
				__tui_19.AddChild(__tui_29)
			}
			__tui_30 := tui.New(
				tui.WithHR(),
				tui.WithBorder(tui.BorderSingle),
			)
			__tui_19.AddChild(__tui_30)
		}
		__tui_31 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithFlexGrow(1),
			tui.WithScrollable(tui.ScrollVertical),
			tui.WithScrollbarStyle(tui.NewStyle().Foreground(tui.Cyan)),
			tui.WithScrollbarThumbStyle(tui.NewStyle().Foreground(tui.BrightCyan)),
			tui.WithScrollOffset(0, m.pageScroll.Get()),
		)
		m.pageRef.Set(__tui_31)
		if len(pages) == 0 {
			__tui_32 := tui.New(
				tui.WithText("（没有匹配的画纸）"),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_31.AddChild(__tui_32)
		}
		for i, p := range pages {
			_ = i
			if m.focus.Get() == 1 && i == m.pageCur.Get() {
				__tui_33 := tui.New(
					tui.WithText(m.pageRow(i, p)),
					tui.WithBackground(tui.NewStyle().Background(tui.BrightBlack)),
					tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
				)
				__tui_31.AddChild(__tui_33)
			} else {
				__tui_34 := tui.New(
					tui.WithText(m.pageRow(i, p)),
					tui.WithTextStyle(tui.NewStyle().Dim()),
				)
				__tui_31.AddChild(__tui_34)
			}
		}
		__tui_19.AddChild(__tui_31)
	}
	__tui_10.AddChild(__tui_19)
	__tui_0.AddChild(__tui_10)
	__tui_35 := tui.New(
		tui.WithHR(),
		tui.WithBorder(tui.BorderSingle),
	)
	__tui_0.AddChild(__tui_35)
	__tui_36 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithPadding(1),
	)
	__tui_37 := tui.New(
		tui.WithText(helpLine),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_36.AddChild(__tui_37)
	__tui_0.AddChild(__tui_36)

	return __tui_0
}

// updatePropsFields is generated. It copies prop fields from fresh onto
// the receiver. When you override UpdateProps, call this helper instead
// of hand-maintaining the copy list.
func (m *manager) updatePropsFields(fresh tui.Component) {
	f, ok := fresh.(*manager)
	if !ok {
		return
	}
	m.opts = f.opts
	m.srv = f.srv
	m.loading = f.loading
}

func (m *manager) UpdateProps(fresh tui.Component) {
	m.updatePropsFields(fresh)
}

var _ tui.PropsUpdater = (*manager)(nil)

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (m *manager) bindAppFields(app *tui.App) {
	if m.boards != nil {
		m.boards.BindApp(app)
	}
	if m.detail != nil {
		m.detail.BindApp(app)
	}
	if m.status != nil {
		m.status.BindApp(app)
	}
	if m.busy != nil {
		m.busy.BindApp(app)
	}
	if m.serverUp != nil {
		m.serverUp.BindApp(app)
	}
	if m.url != nil {
		m.url.BindApp(app)
	}
	if m.boardCur != nil {
		m.boardCur.BindApp(app)
	}
	if m.pageCur != nil {
		m.pageCur.BindApp(app)
	}
	if m.focus != nil {
		m.focus.BindApp(app)
	}
	if m.filter != nil {
		m.filter.BindApp(app)
	}
	if m.filtering != nil {
		m.filtering.BindApp(app)
	}
	if m.showAll != nil {
		m.showAll.BindApp(app)
	}
	if m.boardScroll != nil {
		m.boardScroll.BindApp(app)
	}
	if m.pageScroll != nil {
		m.pageScroll.BindApp(app)
	}
}

func (m *manager) BindApp(app *tui.App) {
	m.bindAppFields(app)
}

var _ tui.AppBinder = (*manager)(nil)

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener     = (*manager)(nil)
	_ tui.WatcherProvider = (*manager)(nil)
)
